---
name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (repo)
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: vx.x.x
      - name: Deno (version)
        run: deno --version
      - name: Deno format (check)
        run: deno fmt --check
      - name: Deno lint
        run: deno lint
      - name: Deno publish
        run: deno publish
